### ISSUE TITLE
Latest version of streamlit-authenticator not working with streamlit 1.33.

### ISSUE THREAD

**Issue by mparacha7** [mkhorasani/Streamlit-Authenticator#215]
AttributeError: module 'streamlit' has no attribute 'context'

Do we have to upgrade to latest version of streamlit , I don't want to upgrade as it messes up my css styling. 

![sterror](https://github.com/user-attachments/assets/b0966575-4d64-43e4-bdf6-eb6ca43384c3)

**Comment by mkhorasani** [comment]
Hi @mparacha7, yes unfortunately there's no other choice, you will have to upgrade to at least streamlit v1.37.0.
